language: python
dist: focal
sudo: true

stages:
  - lint
  - unittest
  - systest

inc_before_install: &inc_before_install
  # Setup the Postgres repositories
  - sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
  - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  - sudo apt update

inc_install: &inc_install
  # Setup build deps
  - sudo apt install -y libsnappy-dev
  - sudo apt install -y postgresql-${PG_VERSION}
  # Setup common python dependencies
  - pip install -r requirements.txt
  - pip install -r requirements.dev.txt
  - pip install -e .

inc_unittest: &inc_unittest
  - make unittest

inc_systest: &inc_systest
  - make systest

jobs:
  allow_failures:
    # Don't require python to succeed
    - python: nightly

  include:
    # Run linters with our "primary" Python version.
    - stage: lint
      python: 3.6
      env: [PG_VERSION=9.6]
      name: fmt
      before_install: *inc_before_install
      install: *inc_install
      script:
        - make fmt
        - if [ $(git diff --name-only --diff-filter=ACMR | wc -l ) != 0 ]; then
          echo "Reformatting failed! Please run make fmt on your commits and resubmit!" 1>&2 ;
          git diff ;
          exit 1 ;
          fi

    - stage: lint
      python: 3.6
      env: [PG_VERSION=9.6]
      name: lint
      before_install: *inc_before_install
      install: *inc_install
      script:
        - make lint

    - stage: lint
      python: 3.6
      env: [PG_VERSION=9.6]
      name: typecheck
      before_install: *inc_before_install
      install: *inc_install
      script:
        - make typecheck

    # Matrix build unittests
    - env: [PG_VERSION=10]
      python: '3.6'
      stage: unittest
      before_install: *inc_before_install
      install: *inc_install
      script: *inc_unittest

    - env: [PG_VERSION=11]
      python: '3.6'
      stage: unittest
      before_install: *inc_before_install
      install: *inc_install
      script: *inc_unittest

    - env: [PG_VERSION=12]
      python: '3.6'
      stage: unittest
      before_install: *inc_before_install
      install: *inc_install
      script: *inc_unittest

    - env: [PG_VERSION=9.6]
      python: '3.6'
      stage: unittest
      before_install: *inc_before_install
      install: *inc_install
      script: *inc_unittest

    - env: [PG_VERSION=10]
      python: '3.7'
      stage: unittest
      before_install: *inc_before_install
      install: *inc_install
      script: *inc_unittest

    - env: [PG_VERSION=11]
      python: '3.7'
      stage: unittest
      before_install: *inc_before_install
      install: *inc_install
      script: *inc_unittest

    - env: [PG_VERSION=12]
      python: '3.7'
      stage: unittest
      before_install: *inc_before_install
      install: *inc_install
      script: *inc_unittest

    - env: [PG_VERSION=9.6]
      python: '3.7'
      stage: unittest
      before_install: *inc_before_install
      install: *inc_install
      script: *inc_unittest

    - env: [PG_VERSION=10]
      python: '3.8'
      stage: unittest
      before_install: *inc_before_install
      install: *inc_install
      script: *inc_unittest

    - env: [PG_VERSION=11]
      python: '3.8'
      stage: unittest
      before_install: *inc_before_install
      install: *inc_install
      script: *inc_unittest

    - env: [PG_VERSION=12]
      python: '3.8'
      stage: unittest
      before_install: *inc_before_install
      install: *inc_install
      script: *inc_unittest

    - env: [PG_VERSION=9.6]
      python: '3.8'
      stage: unittest
      before_install: *inc_before_install
      install: *inc_install
      script: *inc_unittest

    - env: [PG_VERSION=10]
      python: nightly
      stage: unittest
      before_install: *inc_before_install
      install: *inc_install
      script: *inc_unittest

    - env: [PG_VERSION=11]
      python: nightly
      stage: unittest
      before_install: *inc_before_install
      install: *inc_install
      script: *inc_unittest

    - env: [PG_VERSION=12]
      python: nightly
      stage: unittest
      before_install: *inc_before_install
      install: *inc_install
      script: *inc_unittest

    - env: [PG_VERSION=9.6]
      python: nightly
      stage: unittest
      before_install: *inc_before_install
      install: *inc_install
      script: *inc_unittest

    # Matrix Build Systests
    - env: [PG_VERSION=10]
      python: '3.6'
      stage: systest
      before_install: *inc_before_install
      install: *inc_install
      script: *inc_systest

    - env: [PG_VERSION=11]
      python: '3.6'
      stage: systest
      before_install: *inc_before_install
      install: *inc_install
      script: *inc_systest

    - env: [PG_VERSION=12]
      python: '3.6'
      stage: unittest
      before_install: *inc_before_install
      install: *inc_install
      script: *inc_systest

    - env: [PG_VERSION=9.6]
      python: '3.6'
      stage: systest
      before_install: *inc_before_install
      install: *inc_install
      script: *inc_systest

    - env: [PG_VERSION=10]
      python: '3.7'
      stage: systest
      before_install: *inc_before_install
      install: *inc_install
      script: *inc_systest

    - env: [PG_VERSION=11]
      python: '3.7'
      stage: systest
      before_install: *inc_before_install
      install: *inc_install
      script: *inc_systest

    - env: [PG_VERSION=12]
      python: '3.7'
      stage: systest
      before_install: *inc_before_install
      install: *inc_install
      script: *inc_systest

    - env: [PG_VERSION=9.6]
      python: '3.7'
      stage: systest
      before_install: *inc_before_install
      install: *inc_install
      script: *inc_systest

    - env: [PG_VERSION=10]
      python: '3.8'
      stage: systest
      before_install: *inc_before_install
      install: *inc_install
      script: *inc_systest

    - env: [PG_VERSION=11]
      python: '3.8'
      stage: systest
      before_install: *inc_before_install
      install: *inc_install
      script: *inc_systest

    - env: [PG_VERSION=12]
      python: '3.8'
      stage: systest
      before_install: *inc_before_install
      install: *inc_install
      script: *inc_systest

    - env: [PG_VERSION=9.6]
      python: '3.8'
      stage: systest
      before_install: *inc_before_install
      install: *inc_install
      script: *inc_systest

    - env: [PG_VERSION=10]
      python: nightly
      stage: systest
      before_install: *inc_before_install
      install: *inc_install
      script: *inc_systest

    - env: [PG_VERSION=11]
      python: nightly
      stage: systest
      before_install: *inc_before_install
      install: *inc_install
      script: *inc_systest

    - env: [PG_VERSION=12]
      python: nightly
      stage: systest
      before_install: *inc_before_install
      install: *inc_install
      script: *inc_systest

    - env: [PG_VERSION=9.6]
      python: nightly
      stage: systest
      before_install: *inc_before_install
      install: *inc_install
      script: *inc_systest
